"""
Django settings for lendit project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import config
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom Apps
    "accounts.apps.AccountsConfig",
    "inventory.apps.InventoryConfig",
    # Third party apps
    "django_summernote",
    "taggit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Custom middleware
    # Checks to see if we need to create a superuser
    "accounts.middleware.check_superuser.CheckSuperuserMiddleware",
]

ROOT_URLCONF = "lendit.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lendit.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")

MEDIA_URL = "/media/"

MEDIAL_ROOT = os.path.join(BASE_DIR, "media/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}


# Our custom user model
AUTH_USER_MODEL = "accounts.CustomUser"


# Summernote settings - https://github.com/lqez/django-summernote
# SUMMERNOTE_THEME = 'bs4'

SUMMERNOTE_CONFIG = {
    "iframe": True,
    "css": (
        "//stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css",
        "//cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css",
        "//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs4.min.css",
    ),
    "js": (
        "//code.jquery.com/jquery-3.5.1.min.js",
        "//cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js",
        "//cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/10.32.0/js/vendor/jquery.ui.widget.min.js",
        "//cdnjs.cloudflare.com/ajax/libs/blueimp-file-upload/10.32.0/js/jquery.fileupload.min.js",
        "//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.20/summernote-bs4.min.js",
    ),
    "attachment_require_authentication": True,
    "attachment_filesize_limit": 20 * 1024 * 1024,
    "width": "900",
    "height": "500",
    "summernote": {
        "toolbar": [
            ["style", ["style"]],
            ["font", ["bold", "italic", "underline", "clear"]],
            ["fontname", ["fontname"]],
            ["fontsize", ["fontsize"]],
            ["height", ["height"]],
            ["color", ["color", "clear"]],
            ["misc", ["undo", "redo"]],
            [
                "para",
                [
                    "ul",
                    "ol",
                    "paragraph",
                ],
            ],
            ["insert", ["link", "picture", "video", "hr", "table"]],
            ["view", ["fullscreen", "codeview", "help"]],
        ],
        "fontNames": [
            "Arial",
            "Arial Black",
            "Comic Sans MS",
            "Courier New",
            "Times New Roman",
            "Verdana",
            "Helvetica",
            "Georgia",
            "Impact",
        ],
        "fontSizes": [
            "8",
            "9",
            "10",
            "11",
            "12",
            "14",
            "16",
            "18",
            "20",
            "24",
            "28",
            "32",
            "36",
            "48",
            "64",
        ],
    },
}


DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
# django-taggit Settings - https://django-taggit.readthedocs.io/en/latest/getting_started.html
TAGGIT_CASE_INSENSITIVE = True
