# Generated by Django 5.2.6 on 2025-10-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_checked_in_item_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='checked_in',
            new_name='checked_in_at',
        ),
    ]
