# Generated by Django 5.2.6 on 2025-10-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowevent',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
