# Generated by Django 5.2.6 on 2025-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_inventorytag_inventorytaggeditem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[
                    ("av", "Available"),
                    ("br", "Borrowed"),
                    ("ls", "Lost"),
                    ("nr", "Needs Repair"),
                    ("re", "Needs Replacing"),
                    ("pc", "Pending Checkin"),
                    ("rs", "Reserved"),
                ],
                default="av",
                max_length=3,
            ),
        ),
    ]
